config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  get 'students/:id', to: 'students#show'
  get 'schools/index'
  get 'schools/:id', to: 'schools#show'
  get 'people/index'
  get 'people/add'
  post 'people/add', to: 'people#create'
  get 'people/find'
  post 'people/find', to: 'people#find'
  get 'people/:id', to: 'people#show'
  get 'people/edit/:id', to: 'people#edit'
  patch 'people/edit/:id', to: 'people#update'
  delete 'people/delete/:id', to: 'people#delete'
  get 'msgboard/index'
  post 'msgboard/index'
  get 'start/index' => 'start#index'
  post 'start/index' => 'start#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  validates :name, presence: {message: "Name が入力されていません"}
  validates :age, presence: {message: "Age が入力されていません"}
  validates :age, numericality: {only_integer: true, message: "数値ではありません"}

  belongs_to :student
end

app/models/school.rb
class School < ApplicationRecord
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  # has_many :people
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/msgboard_controller.rb
class MsgboardController < ApplicationController
  layout 'msgboard'

  def initialize
    super
    begin
      @msg_data = JSON.parse(File.read("data.txt"))
    rescue => exception
      @msg_data = Hash.new
    end
    File.write("data.txt", @msg_data.to_json)
  end

  def index
    @header = 'メッセージボード'
    @footer = 'studyRails'
    if request.post? then
      obj = MyData.new(params['name'], params['email'], params['msg'])
      @msg_data[@msg_data.length] = obj
      data = @msg_data.to_json
      File.write("data.txt", data)
      @msg_data = JSON.parse(data)
    end
  end
end

class MyData
  attr_accessor :name
  attr_accessor :mail
  attr_accessor :msg

  def initialize(name, mail, msg)
    @name = name
    @mail = mail
    @msg = msg
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  protect_from_forgery
  layout 'start'

  def index
    @header = 'studyRails'
    @footer = 'link'
    @msg = 'Person Data'
    @data = Person.all
    # render layout: 'start'
  end

  def add
    @msg = "add new data."
    @person = Person.new
    @errors = Hash.new
  end

  def create
    if request.post?
      person = Person.create(person_params)
      if person.valid?
        redirect_to '/people/index'
      else
        @errorMessages = person.errors
        render 'add'
      end
    end
  end

  def show
    @msg = "Indexed data."
    @data = Person.find(params[:id])
  end

  def edit
    @msg = "edit data.[id = " + params[:id] + "]"
    @person = Person.find(params[:id])
  end

  def update
    obj = Person.find(params[:id])
    obj.update(person_params)
    redirect_to '/people/index'
  end

  def delete
    obj = Person.find(params[:id])
    obj.destroy
    redirect_to '/people/index'
  end

  def find
    @msg = 'please type search word...'
    @people = Array.new
    if request.post? then
      @people = Person.where(name: params[:find])
    end
  end

  private

  def person_params
    params.require(:person).permit(:name, :age)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  protect_from_forgery
  layout 'start'

  def index
    @header = 'studyRails'
    @footer = 'link'
    @msg = 'School Data'
    @data = School.all
  end

  def show
    @msg = "Indexed data."
    @data = School.find(params[:id])
  end
end

app/controllers/start_controller.rb
class StartController < ApplicationController

  def index()
    @title = "Hello Rails!:"
    @header = "studyRails"
    @footer = "link"
    if request.post?
      @msg = params[:input]
    else
      @msg = "Not POST"
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  protect_from_forgery
  layout 'start'

  def index
    @header = 'studyRails'
    @footer = 'link'
    @msg = 'Students Data'
    @data = Student.all
    # @data = Student.includes(:people)
    # @people = Person.all
    # binding.pry
  end

  def show
    @msg = "Indexed data."
    @data = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/msgboard_helper.rb
module MsgboardHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/start_helper.rb
module StartHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/msgboard.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>メッセージボード</title>
</head>

<body class="container text-body">
  <%= render template: 'layouts/start_header' %>
  <%= yield %>
  <%= render template: 'layouts/start_footer' %>
</body>

</html>

app/views/layouts/start.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <title><%= @title %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="container text-body">
  <%= render template: 'layouts/start_header' %>
  <%= yield %>
  <%= render template: 'layouts/start_footer' %>
</body>

</html>

app/views/layouts/start_footer.html.erb
<div class="mt-5 text-right small text-dark border-bottom border-dark">
  <%= @footer %>
</div>

app/views/layouts/start_header.html.erb
<h1 class="display-4 text-center mt-1 mb-4 text-primary">
  <%= @header %>
</h1>

app/views/msgboard/index.html.erb
<%=  form_tag(controller: "msgboard", action: "index") do %>
<div class="form-group">
  <label for="name">名前</label>
  <%= text_field_tag("name", "", {class: "form-control"}) %>
</div>
<div class="form-group">
  <label for="mail">メール</label>
  <%= text_field_tag("mail", "", {class: "form-control"}) %>
</div>
<div class="form-group">
  <label for="msg">メッセージ</label>
  <%= text_field_tag("msg", "", {class: "form-control"}) %>
</div>
<%= submit_tag("Send", {class: "btn btn-primary"}) %>
<% end %>

<table class="table mt-4">
  <tr>
    <th style="width:50%">メッセージ</th>
    <th>名前</th>
    <th>メール</th>
  </tr>
  <% @msg_data.each do |key, obj| %>
  <tr>
    <td class="msg"><%= obj['msg'] %></td>
    <td class="name"><%= obj['name'] %></td>
    <td class="mail"><%= obj['mail'] %></td>
  </tr>
  <% end %>
</table>

app/views/people/add.html.erb
<h1 class="display-4 text-primary"><a href="/people/index" style="text-decoration: none">People#add</a></h1>
<p><%= @msg %></p>
<% if @errorMessages %>
<% @errorMessages.values.each do |error| %>
  <p><%= error %></p>
<% end %>
<% end%>
<%= form_with model: Person.new, url: people_add_path do |form| %>
<div class="form-group">
  <label for="name">Name</label>
  <%= form.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <label for="age">Age</label>
  <%= form.text_field :age, class: "form-control" %>
</div>
<%= form.submit "登録", class: "btn btn-primary" %>
<% end %>

app/views/people/edit.html.erb
<h1 class="display-4 text-primary"><a href="/people/index" style="text-decoration: none">People#edit</a></h1>
<p><%= @msg %></p>
<%= form_with model: @person, url: '' do |form| %>
<div class="form-group">
  <label for="name">Name</label>
  <%= form.text_field :name, class: "form-control" %>
</div>
<div class="form-group">
  <label for="age">Age</label>
  <%= form.text_field :age, class: "form-control" %>
</div>
<%= form.submit "更新",class: "btn btn-primary" %>
<% end %>

app/views/people/find.html.erb
<h1 class="display-4 text-primary"><a href="/people/index" style="text-decoration: none;">People#Find</a></h1>
<p><%= @msg %></p>
<%= form_with model: @person do |form| %>
<div class="form-group">
  <label for="find">Find</label>
  <%= form.text_field("find", {class: "form-control"}) %>
</div>
<%= form.submit("Click", {class: "btn btn-primary"}) %>
<% end %>

<table class="table">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Age</th>
  </tr>
  <% @people.each do |obj| %>
  <td><%= obj.id %></td>
  <td><%= obj.name %></td>
  <td><%= obj.age %></td>
  <% end %>
</table>

app/views/people/index.html.erb
<h1 class="display-4 text-primary">People#index</h1>
<p><%= @msg %></p>
<table class="table">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th></th>
  </tr>
  <% @data.each do |obj| %>
  <tr>
    <td><%= obj.id %></td>
    <td><a href="/people/<%= obj.id %>"><%= obj.name %></td>
    <td><a href="/people/edit/<%= obj.id %>">Edit</a>
    <%= link_to("Delete", "/people/delete/#{obj.id}", method: :delete, data: { confirm: "このデータを削除しますか？" }) %>
    </td>
  </tr>
  <% end %>
  <%= link_to("新規登録", "/people/add", class: "btn btn-primary") %>
</table>

app/views/people/show.html.erb
<h1 class="display-4 text-primary"><a href="/people/index" style="text-decoration: none">People#show</a></h1>
<p><%= @msg %></p>
<table class="table">
  <tr>
    <th>Id</th>
    <td><%= @data.id %></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= @data.name %></td>
  </tr>
  <tr>
    <th>Age</th>
    <td><%= @data.age %></td>
  </tr>
</table>

app/views/schools/index.html.erb
<h1 class="display-4 text-primary"><a href="/people/index" style="text-decoration: none;">School#index</h1>
<p><%= @msg %></p>
<table class="table">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <% @data.each do |obj| %>
  </tr>
  <tr>
    <td><%= obj.id %></td>
    <td><a href="/schools/<%= obj.id %>" style="text-decoration: none;"><%= obj.name %></a></td>
  </tr>
  <% end %>
</table>

app/views/schools/show.html.erb
<h1 class="display-4 text-primary"><a href="/schools/index" style="text-decoration: none;">Schools#show</h1>
<p><%= @msg %></p>
<table class="table">
  <tr>
    <th>Id</th>
    <td><%= @data.id %></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= @data.name %></td>
  </tr>
  <% @data.students.each do |obj| %>
  <tr>
    <th>Student</th>
    <td><a href="/students/<%= obj.id %>"><%= obj.id %></a></td>
  </tr>
  <% end %>
</table>

app/views/start/index.html.erb
<html>

<head>
  <title>studyRails</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<h1><%= @title %></h1>
<p><%= @msg %></p>
<%= form_tag("index", method: "post") do %>
<%= label_tag(:input, "Input:") %>
<%= text_field_tag(:input, "", {class: "form-control"}) %>
<%= submit_tag("send", {class: "btn btn-primary"}) %>
<% end %>

</html>

app/views/students/index.html.erb
<h1 class="display-4 text-primary"><a href="/people/index" style="text-decoration: none;">Students#index</a></h1>
<p><%= @msg %></p>
<table class="table">
  <tr>
  <th>Id</th>
  <th>School Id</th>
  <th>Person Id</th>
  </tr>
  <% @data.each do |obj| %>

  <tr>
    <td><a href="/students/<%= obj.id %>"><%= obj.id %></a></td>
    <td><a href="/schools/<%= obj.school_id %>"><%= obj.school_id %></a></td>
    <td></td>
  </tr>

  <% end %>
</table>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>